# @package _global_

defaults:
  - /train_config
  - override /model: dinov3_mask_rcnn
  - override /train: dinov3
  - override /augmentation: none
  - _self_

subset:
  percent: 25
  seed: 1337
  premade:
    train_variant: underrepresented_q025/simple_copy_paste

train:
  run_name: premade_dinov3_simple_copy_paste_pct_025_seed_1337

eval:
  mode: full
  visualize_batches: 2

wandb:
  group: premade_dinov3_pct_025_seed_1337
  tags: [premade, dinov3, simple-copy-paste, pct-025]
